# Generated by Django 2.0.5 on 2018-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180711_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
